version: '3.8'

services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    command: /bin/sh
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    environment: 
      - NODE_ENV=development
    tty: true
